### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Imagineer99** [martinshkreli/bitcoinkeygen#1]
What is this? lol

**Comment by chuyqa** [comment]
It's a cryptographic lottery. 

- You load up a list of (real) wallets into a python collection `addlist`
- You run main.py and it generates a pub/priv key pair
- If the pair it generated is part of `addlist`, (Meaning you generated a private key to an existing wallet) it saves the private key. 

In theory this should never have a hit.. But kudos to Martin for trying ;).
